source ~/stackrc

openstack overcloud delete overcloud -y

BUILTINS=/usr/share/openstack-tripleo-heat-templates/environments

set --

# Use templates, without that argument, builtins will not be found
set -- "$@" --templates

# These need to be specified here
set -- "$@" --networks-file /home/stack/osp17_deployment/TripleO/network/network_data.yaml
set -- "$@" --roles-file /home/stack/osp17_deployment/TripleO/roles_data.yaml

# Use pre-provisioned overcloud nodes (`openstack overcloud node provision`)
# This is not described in the docs, sadly.
set -- "$@" --deployed-server

set -- "$@" --ntp-server clock.redhat.com,time1.google.com,time2.google.com,time3.google.com,time4.google.com

# generated by `openstack overcloud network provision`
set -- "$@" -e ~/templates/overcloud-networks-deployed.yaml
# generated by `openstack overcloud network vip provision`
set -- "$@" -e ~/templates/overcloud-vip-deployed.yaml

# enable debug logs
set -- "$@" -e $BUILTINS/debug.yaml
# location of overcloud container registries
set -- "$@" -e /home/stack/osp17_deployment/TripleO/containers-prepare-parameter.yaml

# OVN is the default networking mechanism driver in OSP 17.0. However, to have the
# deployment working, this environment file MUST be added to the openstack overcloud
# deploy command. This is only said in a small note a few paragraphs before the actual
# command invocation.
#set -- "$@" -e $BUILTINS/services/neutron-ovn-ha.yaml
set -- "$@" -e $BUILTINS/services/neutron-ovn-dvr-ha.yaml

# Since we also have DPDK compute nodes, we need this extra file. It is not referenced
# anywhere in the OSP deployment guide.
#set -- "$@" -e $BUILTINS/services/neutron-ovn-dpdk.yaml
#set -- "$@" -e /home/stack/osp17_deployment/TripleO/dpdk-config.yaml

# Enable this if we have sriov compute nodes
set -- "$@" -e $BUILTINS/services/neutron-ovn-sriov.yaml
set -- "$@" -e /home/stack/osp17_deployment/TripleO/sriov-config.yaml

# Override default settings from roles. These files can be modified and the command
# executed again to update the cluster configuration.
set -- "$@" -e /home/stack/osp17_deployment/TripleO/global-config.yaml
# generated by `openstack overcloud node provision`
set -- "$@" -e ~/templates/overcloud-baremetal-deployed.yaml

# Provide settings for ovn-bgp-agent to work
set -- "$@" -e $BUILTINS/services/frr.yaml
#set -- "$@" -e /usr/share/openstack-tripleo-heat-templates/deployment/frr/frr-container-ansible.yaml
#set -- "$@" -e /home/stack/osp17_deployment/TripleO/frr-parameters.yaml
#set -- "$@" -e /home/stack/osp17_deployment/TripleO/frr.yaml
#set -- "$@" -e /home/stack/osp17_deployment/TripleO/podman-insecure-registries.yaml
set -- "$@" -e /home/stack/osp17_deployment/TripleO/bgp_environment.yaml
set -- "$@" --disable-protected-resource-types
#set -- "$@" -e /home/stack/templates/overcloud_images.yaml
# run the actual deployment using all args
openstack overcloud deploy "$@"
