parameter_defaults:
  #  ContainerFrrImage: registry-proxy.engineering.redhat.com/rh-osbs/rhosp17-openstack-frr:17.0.1
  #  ContainerOvnBgpAgentImage: registry-proxy.engineering.redhat.com/rh-osbs/rhosp17-openstack-ovn-bgp-agent:17.0.1
  ContainerFrrImage: undercloud.ctlplane.localdomain:8787/rh-osbs/rhosp17-openstack-frr:17.0
  ContainerOvnBgpAgentImage: undercloud.ctlplane.localdomain:8787/rh-osbs/rhosp17-openstack-ovn-bgp-agent:17.0
  
  FrrOvnBgpAgentDriver: 'ovn_bgp_driver'
  FrrBfdEnabled: true
  FrrBgpEnabled: true
  FrrBgpAsn: 64999
  FrrBgpIpv4AllowASIn: true
  FrrBgpIpv6AllowASIn: true
  FrrBgpUplinks: ['nic4']
  FrrBgpUplinksScope: internal
  FrrLogLevel: debugging
  FrrBgpIpv4SrcNetwork: main_network
  FrrBgpIpv6SrcNetwork: main_network_ipv6
