resource_registry:
# Specify the relative/absolute path to the config files you want to use for override the default.
  OS::TripleO::ComputeSriov::Net::SoftwareConfig: OS::Heat::None


parameter_defaults:
    OvercloudComputeSriovFlavor: computebaremetal
    NeutronNetworkVLANRanges: 'datacentre1:109:115,datacentre2:116:119'
    NeutronBridgeMappings: 'datacentre1:br-provider1,datacentre2:br-provider2'

    ComputeSriovParameters:
      IsolCpusList: 4-23,28-47
      KernelArgs: default_hugepagesz=2GB hugepagesz=2G hugepages=16 amd_iommu=on iommu=pt numa_balancing=disable processor.max_cstate=0 isolcpus=4-23,28-47
      NovaReservedHostMemory: 4096
      NovaComputeCpuSharedSet: 0-3,24-27
      NovaComputeCpuDedicatedSet: 4-23,28-47

      #DerivePciWhitelistEnabled: true
      NovaPCIPassthrough:
        - devname: "eno1"
          trusted: "true"
          physical_network: "datacentre1"
          #vendor_id: "15b3"
          #product_id: "1018"
        - devname: "eno2"
          trusted: "true"
          physical_network: "datacentre2"
          #vendor_id: "15b3"
          #product_id: "1018"
      NeutronSriovAgentExtensions: "qos"

